# Generated by Django 3.1.4 on 2020-12-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='members',
            field=models.ManyToManyField(through='app.InvestorsChoice', to='app.Startup'),
        ),
    ]
