# Generated by Django 3.1.4 on 2020-12-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201221_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
