# Generated by Django 3.1.4 on 2020-12-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_of_company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name_of_company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CR', 'Не выбрано'), ('FN', 'Фонд'), ('CM', 'Компания'), ('PR', 'Частный')], default='CR', max_length=10, verbose_name='type'),
        ),
    ]
